export const SITE_URL = "https://chitranjan.me";
export const PHONE_NO = "+919113178457";
export const EMAIL = "chitranjankumargupta123@gmail.com";
export const ALTERNATE_EMAIL = "chitranjankumargupta@outlook.com";
export const FULL_NAME = "Chitranjan Kumar Gupta";
export const NAME = "Chitranjan Gupta";
export const USERNAME = "chitranjan-gupta";
export const GITHUB_PROFILE = "https://github.com/chitranjan-gupta";
export const GOOGLE_ANALYTICS_ID = process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID!;
export const GOOGLE_TAG_MANAGER_ID = process.env.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID!;
export const GOOGLE_SEARCH_CONSOLE_ID = process.env.NEXT_PUBLIC_GOOGLE_SEARCH_CONSOLE_ID!